server:
  port: 8003

spring:
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      ttl: ${REDIS_TTL}

app:
  dodam:
    key: ${DODAM_KEY}
    login-endpoint: ${LOGIN_ENDPOINT}
    token-endpoint: ${TOKEN_ENDPOINT}
  jwt:
    secret: ${JWT_SECRET}
    verify: ${JWT_VERIFY}
    access-expire: ${ACCESS_EXPIRE}
    refresh-expire: ${REFRESH_EXPIRE}

logging.level:
  org.springframework.boot.autoconfigure: ERROR

